
"""SMART _RESUME_ PRASER.PYB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LL2XynGL2GYDwQe7Dosmnig97bp_ZdbM
"""

!pip install streamlit

!pip install PyMuPDF python-docx

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import file_parser
import text_cleaner
import nlp_extractor
import parser

def format_resume_summary(data):
    return f"""Parsed Resume Summary:
Job Title: {data.get('job_title', 'N/A')}
Education: {data.get('education', 'N/A')}
Skills: {', '.join(data.get('skills', []))}"""
Name: {data.get('name','N/A')}
Certifications: {', '.join(data.get('certifications', []))}
Experience: {data.get('experience', 'N/A')}
Summary: {data.get('summary', 'N/A')}"""

import parser
resume_file = "GCHARANSAI RESUME.pdf"
parsed_data = parser.parse_resume(resume_file)
print(format_resume_summary(parsed_data))

